# Generated by Django 4.2.3 on 2023-08-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InmunoDetecta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
