# Generated by Django 4.2.3 on 2023-10-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InmunoDetecta', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='diagnostico_aprobacion',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
